--- 
document:
  name: "Contratto di Servizio Portale Utente CRM"
  description: "Questo documento contiene il contratto di servizio SLA - Service Level Agreement, per i fruitori del servizio Portale Utente, basato su CRM vtiger."
  tags: 
    - "portale utente"
    - "crm"
