document:
  name: Contratto di Servizio - Portale Utente - CRM Vtiger
  short-name: SLA-Portal
  author: cittametropolitananapoli
  description: |
    Questo repository contiene il contratto di servizio SLA - Service Level Agreement, per i fruitori del servizio Portale Utente, basato su CRM vtiger. Il Portale Utente è un servizio ad uso esclusivo dei redattori interni, per la gestione delle richieste di pubblicazione sul sito istituzionale della Città Metropolitana di Napoli.
  license: CC-BY 4.0
  audience: redattori dipendenti cmna
  type: Contratto di Servizio
  tags:
      - crm
      - portale utente
