projects:
  - title: Contratto di Servizio - Portale Utente - CRM Vtiger
    short-name: SLA-Portal
    description: |
      Questo repository contiene il contratto di servizio SLA - Service Level Agreement, per i fruitori del servizio Portale Utente, basato su CRM vtiger. Il Portale Utente è un servizio ad uso esclusivo dei redattori interni, per la gestione delle richieste di pubblicazione sul sito istituzionale della Città Metropolitana di Napoli.
    website: http://www.cittametopolitana.na.it
    tags:
      - crm
      - portale utente
    documents:
      - title: Contratto di Servizio - Portale Utente - CRM Vtiger
        repository: contratto-di-servizio-docs

